apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: hpu-decode-claim
  labels:
    llm-d.ai/role: decode
spec:
  spec:
    devices:
      requests:
        - name: intel-gaudi
          exactly:
            deviceClassName: gaudi.intel.com
            count: 4
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: hpu-prefill-claim
  labels:
    llm-d.ai/role: prefill
spec:
  spec:
    devices:
      requests:
        - name: intel-gaudi
          exactly:
            deviceClassName: gaudi.intel.com
            count: 1
